### ISSUE TITLE
Channel Launch Todo

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/exponent#1]
- [ ] Code Review
- [ ] Add @Alymosul as repo admin
- [ ] Add to website
- [ ] Create packagist package

**Comment by atymic** [comment]
Hi @Alymosul, could you create a PR for the code :)

**Comment by atymic** [comment]
ping @Alymosul

**Comment by Alymosul** [comment]
Sorry i'm busy atm due to relocation, i'll try to do it asap.

**Comment by atymic** [comment]
No worries :)

**Comment by atymic** [comment]
ping @Alymosul

**Comment by atymic** [comment]
cc @Alymosul
